admin_tablero:
    path:     /
    defaults: { _controller: AdminBundle:Tablero:index }


admin_pagina:
    path:     /pagina/{id}
    defaults: { _controller: AdminBundle:Pagina:index, id: 0 }
    requirements:
        id: '\d+'

admin_pagina_agregar:
    path:     /pagina/agregar/{id}
    defaults: { _controller: AdminBundle:PaginaAgregar:index, id: 0 }
    requirements:
        id: '\d+'

admin_pagina_editar_item:
    path:     /pagina/editar-item/
    defaults: { _controller: AdminBundle:Pagina:editarItem }
    methods: [POST]
    options:
        expose: true

admin_pagina_guardar_item:
    path:     /pagina/guardar-item/
    defaults: { _controller: AdminBundle:Pagina:guardarItem }
    methods: [POST]

admin_pagina_agregar_guardar:
    path:     /pagina/agregar/guardar
    defaults: { _controller: AdminBundle:PaginaAgregar:guardar }
    methods:  [POST]

admin_pagina_bloques:
    path:     /pagina/bloques/{id}
    defaults: { _controller: AdminBundle:PaginaBloques:index, id: 0 }
    requirements:
        id: '\d+'

admin_pagina_bloques_agregar:
    path:     /pagina/bloques/agregar
    defaults: { _controller: AdminBundle:PaginaBloques:agregarBloque }
    methods:  [POST, GET]

admin_pagina_bloques_agregar_cargar_form:
    path:     /pagina/bloques/agregar/cargar-form
    defaults: { _controller: AdminBundle:PaginaBloques:cargarForm }
    methods:  [POST]
    options:
        expose: true

admin_pagina_bloques_agregar_texto:
    path:     /pagina/bloques/agregar/texto
    defaults: { _controller: AdminBundle:PaginaBloques:agregarTexto }
    methods:  [POST]
    options:
        expose: true

admin_pagina_bloques_guardar_texto:
    path:     /pagina/bloques/guardar/texto
    defaults: { _controller: AdminBundle:PaginaBloques:guardarTexto }
    methods:  [POST]

admin_pagina_eliminar:
    path:     /pagina/eliminar/{id}
    defaults: { _controller: AdminBundle:PaginaAgregar:eliminar, id: 0 }
    requirements:
        id: '\d+'