fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /